services:
  #-------------------------------------------#
  #    Service infrastructure dependencies    #
  #-------------------------------------------#
  mongo:
    image: mongo
    restart: always
    command: "--replSet rs0 --bind_ip_all"
    ports:
      - 27017:27017

  mongosetup:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: "bash /scripts/setup_mongo.sh"

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 3000:3000
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: "minio server --console-address :3000 /data"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  #-------------------------------------------#
  #               Microservices               #
  #-------------------------------------------#
  api-gateway:
    # image: ghcr.io/team-pandora/api-gateway:latest
    build: ./api-gateway
    depends_on:
      - fs-crud
      - storage-service
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 8000
      FS_CRUD_URL: http://fs-crud:8000
      STORAGE_SERVICE_URL: http://storage-service:8000
      SPIKE_ENABLED: true
      SPIKE_AUDIENCE: 2rYAQb~MpuJ5JDk~yBc2tk6wgajjPy
      SPIKE_PUBLIC_KEY_DOWNLOAD_URI: https://ospike.northeurope.cloudapp.azure.com/.well-known/publickey.pem
      SHRAGA_ENABLED: true
      SHRAGA_URL: https://shraga.shraga.branch-yesodot.org
      SHRAGA_CALLBACK_URL: http://localhost/auth/callback
      LINK_SECRET: secret
      SPIKE_CLIENTS_API_SCOPE: api
      KARTOFFEL_URL: http://kartoffel.branch-yesodot.org

  fs-crud:
    # image: ghcr.io/team-pandora/fs-crud:latest
    build: ./fs-crud
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongo:27017/fs-crud?replicaSet=rs0
      MONGO_QUOTAS_COLLECTION_NAME: quotas
      MONGO_STATES_COLLECTION_NAME: states
      MONGO_FS_OBJECTS_COLLECTION_NAME: fsobjects

  storage-service:
    # image: ghcr.io/team-pandora/storage-service:latest
    build: ./storage-service
    environment:
      PORT: 8000
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_USE_SSL: false

  drive-ui:
    # image: ghcr.io/team-pandora/fs-crud:latest
    build: ./drive-ui

  gateway:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
